### ISSUE TITLE
Slight metagame leak with Hidden Effects

### ISSUE THREAD

**Issue by JamzTheMan** [shemetz/pf2e-extempore-effects#13]
If the player has another condition, e.g. Deafened, the separator bar ___ is shown to the player which would indicate there are more "hidden" effects to display (but don't).

![image](https://user-images.githubusercontent.com/8051654/197895525-c0b73063-5989-4845-9821-7dd7bcef06a1.png)

**Comment by shemetz** [comment]
nice find!  thanks, I'll see if I can remove this.

**Comment by shemetz** [comment]
Fixed in v1.5.2
