### ISSUE TITLE
Ghoul Fever cannot be made as Extempore effect

### ISSUE THREAD

**Issue by Ghilteras** [shemetz/pf2e-extempore-effects#14]
I tried to make Ghoul Fever as an Extempore effect but it fails due to `item not found` (yes I imported the compendium)

Is this a known issue?

**Comment by shemetz** [comment]
Works fine for me, both from the compendium ability and from the actor ability (either one works when printed to chat and then right clicked into Extempore Effect).

Are you using the latest versions, pf2e 4.5.1 and Extempore Effects 1.6.0?

Can you explain how you're getting your ghoul fever exactly?

**Comment by Ghilteras** [comment]
I'm sorry @shemetz it's working now, we can close this, I am not sure why it was not working a couple of weeks ago, maybe just because of the version
