### ISSUE TITLE
Bug: Extempore effect names start with ".addedPrefixToExpendedEffectName"

### ISSUE THREAD

**Issue by LMiljak** [shemetz/pf2e-extempore-effects#16]
**Versions**
pf2e Extempore Effects 1.6.1
libWrapper 1.12.11.0
Pathfinder 2nd Edition 4.6.3
Foundry VTT version 10, build 291

**Problem**
Whenever you add an extempore effect by right-clicking a chat item, then clicking "Extempore Effect," then the generated name of the created effect will be broken. The name will always have ".addedPrefixToExpendedEffectName" before the actual name. For instance, if I have a chat card for the "Negative Healing" passive ability, the generated name of the extempore effect will be ".addedPrefixToExpendedEffectNameNegative Healing."

![image](https://user-images.githubusercontent.com/9739325/211031623-2096856e-72c0-4b9b-8b04-a294dd2ffcfa.png)
![image](https://user-images.githubusercontent.com/9739325/211031743-9a8de0a8-538d-441b-9612-b379e0ed2dab.png)

This problem occured on a fresh world with only this module and the libWrapper module enabled, with the versions above.

**Comment by shemetz** [comment]
Fixed in v1.6.2

**Comment by LMiljak** [comment]
Thanks! This is a great module btw... just wanted that to be said :)
