### ISSUE TITLE
Conflict with Pf2e Effect Descriptions

### ISSUE THREAD

**Issue by MrChessur** [shemetz/pf2e-extempore-effects#17]
Pf2e Effect Descriptions(https://github.com/reonZ/pf2e-effect-description) adds a few contextual hotkeys for the effect panel. One of these is the "open sheet" which, as this module does, opens the sheet of the effect. The only issue is they are mapped to different hotkeys. Both show up in the tooltip, but extempore effects (shift+click) overrides the usage of the other effect descriptions (ctrl+click), making it not usable and instead it just works like regular left click. Not asking for this one to specifically change, but to maybe get a unified choice between the two.

![image](https://user-images.githubusercontent.com/28309284/212220365-d577c9bd-60e3-436c-b750-405b1d646ac9.png)

**Comment by shemetz** [comment]
I can't decide, so I'm gonna make the community help me decide by using a survey.

https://discord.com/channels/880968862240239708/880969174661353484/1065271833580015747

**Comment by shemetz** [comment]
Status so far (after 30 minutes):  1 vote for Ctrl + Left Click, 1 vote for Shift + Right Click, 6 votes for Shift + Left Click, and 9 votes for "make it configurable".

I'll check this again tomorrow, but so far, looks like I'm going to keep Shift + Left Click as the default and possibly add a setting to make it use Ctrl instead.

**Comment by shemetz** [comment]
Up to 11 for Shift+LC and 11 for configurability.

I'm going to make it configurable, but default to Shift+LC.

**Comment by JDCalvert** [comment]
I was a little late to the party, but could the configurable-ness include disabling the shortcut altogether? I specifically found the same problem as the original reporter.

**Comment by shemetz** [comment]
Fixed in module version v1.6.3+
