### ISSUE TITLE
Crash when dragging tokens?

### ISSUE THREAD

**Issue by NikolasTzimoulis** [shemetz/pf2e-extempore-effects#18]
Sometimes when I drag tokens the foundry page crashes (usually F5 or ctrl+F5 fixes it). Last time it happened I checked the console and it said
```
Uncaught TypeError: Cannot read properties of null (reading 'clear')
[No packages detected]
    at z.clear (pixi-graphics-smooth.umd.min.js:2)
    at TokenPF2e._refreshTarget (foundry.js:46327)
    at TokenLayerPF2e._animateTargets (foundry.js:37292)
    at t.emit (pixi.min.js:8)
    at e.update (pixi.min.js:8)
    at _tick (pixi.min.js:8)
```

I was told on discord this has to do with extempore effects and a bug involving missing images. Please take a look.

**Comment by shemetz** [comment]
Didn't manage to replicate.  Please reopen if you do!

**Comment by NikolasTzimoulis** [comment]
I managed to track down the exact cause, it had nothing to do with extempore effects [but instead is related to drag ruler.](https://github.com/League-of-Foundry-Developers/pf2edragruler/issues/39)
