### ISSUE TITLE
Feature Request: Create counter effects from single rolls

### ISSUE THREAD

**Issue by elemorelli** [shemetz/pf2e-extempore-effects#28]
Is there any way to create a Counter Effect from a simple dice roll?

It would be great for tracking Breath Weapons or similar abilities. I doesn't need to have any description or icon to be helpful, just a counter effect would suffice.

I imagine it would be something like this:

![imagen](https://github.com/shemetz/pf2e-extempore-effects/assets/1661552/7d93f38e-e8fe-4353-8f02-943aea3e48f8)

![imagen](https://github.com/shemetz/pf2e-extempore-effects/assets/1661552/2a25e7a3-c412-400e-96e2-fb3d99ce5cb5)

**Comment by shemetz** [comment]
In that situation, I think it's easiest to just generate a new extempore effect with Ctrl+Shift+E and then just write the die roll result in the name.  Does that solve your use case?

**Comment by shemetz** [comment]
![image](https://github.com/shemetz/pf2e-extempore-effects/assets/6516621/bb3c219c-c8e7-4ddc-b511-c9b73af825a6)

Adding this feature now - it won't use counters, but rather, directly set the number of rounds remaining.

**Comment by shemetz** [comment]
Added in v1.80

**Comment by elemorelli** [comment]
Amazing! 😄
