### ISSUE TITLE
Quirk regarding afflictions that expire due to Maximum Duration

### ISSUE THREAD

**Issue by Gray-Light** [shemetz/pf2e-extempore-effects#29]
When dealing with poisons with a set/max duration, I've noticed something odd. The actual duration of an Extempore Effect can expire prematurely if the poisoned character scored higher in initiative than the monster inflicting the poison.

The quickest way to practically demonstrate this is if you take an NPC monster with the ability to apply a round-by-round poison affliction, and put that creature into an encounter with a PC. I'll attempt to outline the two conflicting scenarios below. **Scenario A** has the venomous monster acting BEFORE the PC in initiative. **Scenario B** has the venomous monster acting AFTER the PC. I'm using a reefclaw in these examples. But for the sake of simplicity, I manually set Reefclaw Venom to have a duration of only 1 round, rather than the default 4 rounds. All of these examples assume the PC fails all saves versus this particular affliction.

---

### Scenario A
In this scenario, the venomous monster goes first in initiative.

**Encounter Round 1:**

_Reefclaw's Turn!_ 
The Reefclaw poisons the PC via a Strike. The PC suffers the immediate effects of the affliction (assuming no onset time), and the GM adds an Extempore Effect to the PC's token.

_PC's Turn!_
The PC fights back. At the end of this turn, the PC makes saves for ongoing afflictions, as per the [second dot point on this page (AoN link).](https://2e.aonprd.com/Rules.aspx?ID=438) Assuming they failed, they take the effect of the next stage of the affliction.

**Encounter Round 2:**

_Reefclaw's Turn!_
Reefclaw takes it's turn. The Extempore Effect is still marked as active. (This might be argued to be an error as far as RAW is concerned, see further discussion below)

_PC's Turn!_
The PC's turn begins. The Extempore Effect immediately expires, and is marked as such on the HUD. Afterwards, the PC takes their turn, and the GM calls for no further Fort saves for the expired affliction.

**Scenario A Synopsis**
In this example, the PC makes **two** relevant Fort rolls (assuming the PC does not suffer ["multiple exposures"](https://2e.aonprd.com/Rules.aspx?ID=369)) before the Extempore Effect expires... One for the initial save, and another one at the end of the PC's turn in round 1.

---

### Scenario B
In this scenario, the PC beat the venomous monster in initiative.

**Encounter Round 1:**
_PC's Turn!_ 
The PC takes their turn.

_Reefclaw's Turn!_
The Reefclaw poisons the PC via a Strike. The PC suffers the immediate effects of the affliction (assuming no onset time), and the GM adds an Extempore Effect to the PC's token.

**Encounter Round 2:**
_PC's Turn!_ 
The PC starts their turn. The Extempore Effect is IMMEDIATELY marked as EXPIRED. The GM assumes Extempore Effect knows what it's talking about, and dismisses the effect with a right-click. The PC takes their actions for the round, and ends their turn without rolling another save for the monster's affliction.

_Reefclaw's Turn!_
The Reefclaw takes its turn.

**Scenario B Synopsis**
In this example, the PC only rolls **one** fort save (the initial save) before the Extempore Effect expires.

---

Now, I'm not going to pretend I'm an expert-proficiency rules-lawyer when it comes to PF2e. In fact, when I noticed this happening with Extempore Effects, I ultimately had to seek help from the nearest group of big-brain PF2 Discord GMs to clarify that this was even technically a problem in relation to the rules-as-written. But the conclusion from those online discussions seemed to rest on Scenario A being the more accurate interpretation, with the affected character needing to roll 2 saves for the full life-cycle of a single-round affliction of this nature.

### Further Discussion/Feature Request
I alluded to this in Scenario A, but it would be nice if we had the option of setting the duration of an Extempore Effect to expire/count down during the turn of someone OTHER than the affected actor. In the case of afflictions, they should (arguably) have their durations count down or expire at the start of the initiative count of the creature that inflicted them. However, unless I'm missing something, Extempore Effects can currently only be set to count down/expire at the start/end of the token they're applied to.

Anyway, I hope all of this was clear enough. I'm still wrestling with the finer points of running PF2e, so mods like this are a literal godsend when it comes to checking, challenging, and verifying my own comprehension of the underlying rules. Cheers! :)

**Comment by shemetz** [comment]
I think this isn't an Extempore Effects problem but a PF2E system problem.  What we need to check is whether this same problem exists when, instead of using the module, you simply create a 1-round effect (in the Items directory) and drag it to the PC in both scenarios, checking what happens.  If exactly the same thing happens, then this is a pf2e system bug (or missing feature).

**Comment by shemetz** [comment]
Though I do see an actual module bug - the module posts the chat message about expiration when the effect has 0 rounds left, even if it still has some turns left (e.g. start of initiative when PC is 2nd in initiative and monster is 3rd).

**Comment by shemetz** [comment]
...and it's a hard bug to fix, because the pf2e system doesn't have any hook for "item just became expired".

**Comment by shemetz** [comment]
Fixing it by not showing expiry chat messages at all for combat round time changes.  Adding this to readme:

> Note that this will not work for tiny 1-round time changes (which happens in combat), because of technical difficulties.
However, this is probably not a problem for you - if you have an effect with a duration measured in rounds, you probably
aren't going to forget about it.

**Comment by shemetz** [comment]
Also, improved behavior of afflictions - they'll end at the end of the turn rather than the start, and they will also have visible stages (start with Stage 1), and they will also have a duration based on the stage 1 duration.  Overall, this doesn't solve your problem, but it makes lots of things easier near it!

(v1.8.0)

**Comment by shemetz** [comment]
Closing this, as I don't think I can improve things further beyond what I mentioned above.
