### ISSUE TITLE
Stage of affliction cannot be displayed when used with Dorako UI's option to adjust effects HUD 

### ISSUE THREAD

**Issue by Fraxinus1753** [shemetz/pf2e-extempore-effects#30]
When used in conjunction with the "Adjust token efects HUD" option from Dorako UI, the stage of afflictions created with Extempore Effects is not visible, as the condition token is too small to contain the entire text. It only displays "Stag...".

It's a minor request, but this option in Dorako UI makes reading conditions on tokens significantly easier and I'd love to be able to use it with this module. This might be resolved by giving the option to only show the stage number on the condition token, without "Stage" written in front of it.

**Comment by shemetz** [comment]
Can you share a screenshot?

Also, is this perhaps a general bug with Dorako UI?  I imagine that many people would want to have afflictions with labels for the stages, and this module just happens to automatically assign these labels.

But yes, if you want I could add a setting (or maybe just automatic behavior when detecting Dorako UI is active) so that stage labesl are "1", "2", etc instead of "Stage 1", "Stage 2", etc.

**Comment by Fraxinus1753** [comment]
Sure! I don't think it's a bug, from what I understand it's simply that Dorako UI's option changes condition tokens to be round and smaller, and they become too small to display "Stage X" in its entirety. I think they are made this way because conditions usually simply display their numerical value. 

![With Dorako UI](https://github.com/shemetz/pf2e-extempore-effects/assets/41876735/ed296023-60e0-42b0-b5a2-7a10f0615a9f)
Here is the screenshot with the option (circled) in Dorako UI active. 

![Without Dorako UI](https://github.com/shemetz/pf2e-extempore-effects/assets/41876735/2c3904fc-35ea-494c-be4c-d73eb43bd02d)
Here without Dorako UI (normal behavior).

![Dorako UI general conditions](https://github.com/shemetz/pf2e-extempore-effects/assets/41876735/427609a3-c68e-480b-9099-b953be811762)
And just so you can see, Dorako UI's behavior with regular conditions. 

An option would be very nice I think, auto-detection might be an overkill as you can use Dorako UI but without the option that makes condition tokens round (when I deactivated the option this morning the token stayed round so I had to deactivate the entire module to make it square again, but I'm pretty certain it worked when I simply deactivated the option yesterday).

**Comment by shemetz** [comment]
This should be fixed with the next version of Dorako UI, probably.  Reopen if not!
