### ISSUE TITLE
Stats on Weak or Elite Creatures

### ISSUE THREAD

**Issue by Neakas** [shemetz/pf2e-extempore-effects#33]
When creating an Effect from the Chat Card it looks like the Savingthrow and Damage Adjustment from Elite or Weak Status of a Monster is not taken into Account:

![grafik](https://github.com/shemetz/pf2e-extempore-effects/assets/6743232/16415e21-15e6-443f-8c95-8425e27e5803)

![grafik](https://github.com/shemetz/pf2e-extempore-effects/assets/6743232/9d12c364-bbb3-4c21-b08c-48a53c677ee6)

**Comment by shemetz** [comment]
Fixed in v1.8.1
