### ISSUE TITLE
Feature Idea: Notifications on expired effects

### ISSUE THREAD

**Issue by shemetz** [shemetz/pf2e-extempore-effects#5]
This notification should apply whenever an Effect's time runs out, either to all effects or only to those that have multiple stages (afflictions), or maybe set by a flag that has a toggle button.

Use case is for when players need to make a roll after a period of time passes,as is common for all afflictions - but note, if this happens they should also have a real duration instead of "unlimited".

Maybe instead of building this feature into the module it's better to have it in the core pf2e system.

**Comment by JamzTheMan** [comment]
A possible alternative/additive to this would be another checkbox to mark a particular effect to *not* auto-delete when expired?

So you can set that Ghoul Fever for 1 day or that poison to an Hour and either get a message and/or see the effect as expired but still on the character so you can make the roll and stage it up/down (for afflictions)

**Comment by shemetz** [comment]
Added in v1.7.0
