### ISSUE TITLE
Ctrl-Shift-E effect causes strikes dialogue to not pop out when targeting creatures

### ISSUE THREAD

**Issue by Fyrexian** [shemetz/pf2e-extempore-effects#8]
Using the keybind to make a custom effect causes the player character's strike buttons to break and dialogue not to pop out when targeting another character.

V10.286 ....  4.1.3 

![image](https://user-images.githubusercontent.com/47077661/193176941-9fdbc520-fc36-47bd-94a6-7475487e8348.png)

**Comment by shemetz** [comment]
Thanks for the report - fixed this in version 1.3.0!
